name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        path: ./releases
